# Generated by Django 4.0.6 on 2022-07-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_price_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_f',
        ),
    ]
