# Generated by Django 4.0.6 on 2022-07-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
