# Generated by Django 4.0.6 on 2022-07-19 10:41

from django.db import migrations, models
import django.forms.widgets
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.forms.widgets.HiddenInput),
        ),
    ]
