# Generated by Django 4.0.6 on 2022-07-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_created_alter_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
