# Generated by Django 4.0.6 on 2022-07-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_comments_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desciprtion',
            field=models.TextField(default='خالی', max_length=100),
        ),
    ]
