# Generated by Django 4.0.6 on 2022-07-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_desciprtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desciprtion',
            new_name='description',
        ),
    ]
